project:
  type: website
  output-dir: docs
  
website:
  title: "Martouzet Physique"
  sidebar:
    background: "#D9E3E4"
    pinned: true
    align: center
    style: "docked"
    contents:
      - section: "Test section"
        contents:
          - href: index.qmd
            text: Home
          - projects.qmd
          - notebook/these.ipynb
          - notebook/intro_graphique.ipynb 
    tools:
      - icon: twitter
        href: https://twitter.com/
      - icon: github
        href: https://github.com/YOURUSERNAME/YOURREPO
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
    left: "&copy; Copyright 2025, Martouzet G."

format:
  html:
    theme:
      light: [cosmo, theme.scss]
      dark: [cosmo, theme-dark.scss]
    toc: false

freeze: auto

editor: source

