project:
  type: website
  output-dir: docs
  
website:
  title: "Martouzet Physique"
  sidebar:
    background: "#D9E3E4"
    pinned: true
    align: center
    style: "docked"
    contents:
      - href: index.qmd
        text: Accueil
      - section: "Test section"
        contents:
          - notebook/these.ipynb
          - notebook/intro_graphique.ipynb 
          - pages_md/figure_tikz.qmd
          - notebook/Article_PÃ©dagogique.ipynb
    tools:
      - icon: linkedin
        href: https://www.linkedin.com/in/gr%C3%A9goire-martouzet-a61786129/
      - icon: github
        href: https://github.com/gregomartophysique/martouzetphysique/
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
    left: "&copy; Copyright 2025, Martouzet G."

format:
  html:
    theme:
      light: [cosmo, theme.scss]
    toc: false

freeze: auto

editor: source

